# string operations
str1='Hello World'

print('1.Capitalize: ',str1.capitalize())
print('2.Center: ',str1.center(20,'*'))
print('3.Count: ',str1.count('o'))
print('4.Find: ',str1.find('e'))
print('5.Index: ',str1.index('d'))
print('6.isalnum: ',str1.isalnum())
print('7.isalpha: ',str1.isalpha())
print('8.islower: ',str1.islower())
print('9.isupper: ',str1.isupper())
print('10.lstrip: ',str1.lstrip())
print('11.rstrip: ',str1.rstrip())
print('12.replace: ',str1.replace('e','b'))
print('13.rjust: ',str1.rjust(20))
print('14.ljust: ',str1.ljust(20))
print('15.endswith: ',str1.endswith('d'))
print('16.startswith: ',str1.startswith('H'))
print('swapcase: ',str1.swapcase())
print('length: ',len(str1))
print('slicing: ',str1[5::3])
print('title: ',str1.title())
print('rfind: ',str1.find('W'))
